# Generated by Django 3.2.25 on 2024-10-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.IntegerField()),
                ('day', models.IntegerField(default=10)),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('med', models.CharField(max_length=100)),
                ('add', models.CharField(max_length=100)),
            ],
        ),
    ]
